gclm:
  download:
    baidu:
      # 百度文库 api
      wenku:
        # doc_id 是文档id
        word: http://47.95.226.123/getDoc.do?docUrl=%s
        # ppt url = "https://wenku.baidu.com/browse/getbcsurl?doc_id=660e3a9b5122aaea998fcc22bcd126fff6055d54&type=ppt&callback=gclm"
        ppt: https://wenku.baidu.com/browse/getbcsurl?doc_id=%s&type=ppt&callback=gclm
        # pdf url = "https://wenku.baidu.com/browse/getbcsurl?doc_id="+doc_id+"&pn=1&rn=99999&type=ppt"
        pdf: https://wenku.baidu.com/browse/getbcsurl?doc_id=%s&type=ppt&callback=gclm
        # txt URL=https://wkretype.bdimg.com/retype/text/'+doc_id+'?rn='+pn+'&type=txt'+md5+'&rsign='+rsign
        txt: https://wkretype.bdimg.com/retype/text/%s?rn=%s&type=txt%s&rsign=%s
        # 文档详情 5ad9b333302b3169a45177232f60ddccda38e62d
        doc: https://wenku.baidu.com/api/doc/getdocinfo?callback=cb&doc_id=%s
#        文档写在路径 /Volumes/Workspace/WenKu
        docPath: /Volumes/Workspace/WenKu/%s/%s.%s

# 数据库链接信息
spring:
  datasource:
    url: jdbc:mysql:///download?characterEncoding=utf-8&&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: gclmroot159
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

# druid 数据源配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #    filters: stat,wall,log4j
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#mybatis-plus 配置
mybatis-plus:
  #mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.baomidou.springboot.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 0
      #logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false